spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mariadb://database-1.cpeoyq8kyjgq.ap-northeast-2.rds.amazonaws.com:3306/project2"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      hibernate:
        SQL: DEBUG


#aws
cloud:
  aws:
    credentials:
      secret-key: ${cloud.aws.credentials.secret-key}
      access-key: ${cloud.aws.credentials.access-key}
    region:
      static: ap-northeast-2
    s3:
      bucket: myawsbucketteam



jwt:
  secret-key-source: ${JWT_SECRET_KEY}